# Étape 1 : Utiliser une image officielle de Node.js
FROM node:18-alpine AS builder

# Définir le répertoire de travail
WORKDIR /usr/src/app

# Copier uniquement package.json et package-lock.json
COPY package.json package-lock.json ./

# Installer les dépendances sans générer de fichiers inutiles
RUN npm install --force

# Copier tout le projet
COPY . .

# Construire l'application React
RUN npm run build

# Étape 2 : Utiliser une image plus légère pour l'exécution
FROM node:18-alpine

WORKDIR /usr/src/app

# Copier uniquement le build final de React
COPY --from=builder /usr/src/app/build ./build

# Installer un serveur web léger (serve)
RUN npm install -g serve

# Exposer le port 3000
EXPOSE 3000

# Lancer l'application avec Serve
CMD ["serve", "-s", "build", "-l", "3000"]
